export const companyInfo = `Baroque Variations Ltd is a multi-faceted indigenous company registered in 2012, dedicated to providing diverse products and services to meet the needs of customers across Nigeria. The company operates several business divisions, including e-commerce, event planning, children’s products, gift solutions, and logistics. Baroque Variations Ltd is committed to quality, customer satisfaction, and innovation, ensuring that all services are delivered with excellence.

Baroque Kiddies (Everything Kids) was established in 2017 and focuses on children’s needs. It offers party planning services for kids, sales of children’s clothing, educational books, toys, and accessories, and is the official distributor for Hasbro toys, currently covering the South region of Nigeria. Baroque Events Pro, launched in 2018, is an online platform that connects customers with event professionals for various occasions such as weddings, parties, and baby dedications. Services include booking MCs, caterers, photographers, makeup artists, and event venues, with access to event centers, hotel halls, and open fields nationwide.

Baroque Gift Ideas, introduced in 2019, simplifies gifting by offering customizable gift cards featuring personal pictures and messages, redeemable at over 100 shopping malls and supermarkets nationwide. It also offers gift packages tailored for occasions like birthdays, graduations, Valentine’s Day, Christmas, Mother’s Day, and Father’s Day. JustBaroque, the e-commerce platform launched in June 2020, provides a wide range of products and services at affordable prices with convenient shopping and doorstep delivery. It is supported by Baroque Express, the logistics division handling nationwide packaging and deliveries. Additional services offered by the company include supplies and general contracts, as well as oil and gas servicing.

All products and services undergo Total Quality Management (TQM) to ensure high standards. A 360-degree Customer Relationship Management (CRM) system is in place to manage customer feedback, experience sharing, product ratings and reviews, and real-time order tracking. The company prioritizes customer feedback to improve offerings and expand services.

The mission of Baroque Variations Ltd is to promote an online platform that supports indigenous brands, offering customers easy access to goods and services at the lowest possible prices. Its vision is to create an unmatched online shopping experience, serving as a one-stop shop for all customer needs.

The company’s core values include passion—striving for innovation, creativity, and excellence in execution; integrity—maintaining honesty, transparency, and commitment in all dealings; teamwork—leveraging the skills of highly talented individuals to achieve collective success; a customer-centric approach—ensuring all decisions and strategies prioritize customer satisfaction; and hard work—continuously pushing for excellence and impactful solutions.

The management team comprises Ijeoma Wabara, Managing Director / CEO, a graduate of Music from the University of Nigeria, Nsukka (UNN), currently completing an MBA at Business School Netherlands (BSN), with 8 years of banking experience and membership in CIBN, ACCA affiliate, and the Rotary Club of Nigeria. Ayodeji Jaccuss Adekoya, Director, holds a B.Sc in Economics (University of Lagos) and an MSc in Operations & Supply Chain Management (Manchester Business School), with over 8 years in banking and shareholder roles in other businesses. Uche Nlemadim, Company Secretary, holds a Bachelor’s degree in Project Management Technology (FUTO), with over 10 years in sales and program management, and is a former Program Manager at JDPC and a member of NIM and CIBN. Chike Ikeoha, Esq., Company Lawyer, specializes in commercial dispute resolution and represents clients in tax, contract, maritime, aviation, and employment cases, holding a BL and LL.B, and membership in the Nigerian Bar Association, International Bar Association, and CIArb (UK).`